### PR TITLE
Adding pom.xml for Maven Central distribution

### PR DESCRIPTION
**Pull request by bocon13**
Also, adding several targets to build.xml to facilitate uploading the maven artifact to Maven Central.

Based on recommendations from Sonatype: http://central.sonatype.org/pages/apache-ant.html

To deploy the artifacts, you need to do the following:
1. Create an account: http://central.sonatype.org/pages/ossrh-guide.html
2. Create the ~/.m2/settings file: http://central.sonatype.org/pages/apache-ant.html (near the bottom)
3. Run "ant setup-stage" to download the maven ant plugin
4. Run "ant stage" to stage the artifacts with sonatype
5. Close and release the repository, wait 15 minutes and it will be in Maven Central.

### CODE REVIEW

**Comment by klacke** [comment]
Nice, so this makes it possible for end user to choose weather they want to use
maven or ant ??

**Comment by klacke** [comment]
You might also want to have the comments above in a README or something, or maybe in the build.xml file so that people know how to use it

**Comment by bocon13** [comment]
Sorry for the delayed reply. The goal of this pull request was to facilitate the creation and upload of a JNC maven artifact to Maven Central. The pom.xml was required because all artifacts require one. I figured that ant was the build tool of choice for this project.

However, if you are interested in allowing end users to use maven to build the project. We would need to add a few more lines to the pom.xml. We could also simplify build.xml, as it's easier to generate an upload artifacts using maven (ant actually calls a maven plugin in this pull request). I can make the changes to the pom.xml and submit another pull request for your review.

Thanks!

**Comment by klacke** [comment]
I don't really know, you'll have to help me out here. I'm not - by even a longshot - a
maven user. The way I understood this, was that you can build the jar with ant, upload to mavencentra, and then use that jar from your normal maven proj. Fine.
I'm not really interested in having a maven build of JNC itself, no.

**Comment by bocon13** [comment]
Ah, I see. That is correct. The pull request lets you build a jar with ant, upload to maven central, and then import jnc into another project using the following:

<dependency>
      <groupId>com.tailf</groupId>
      <artifactId>jnc</artifactId>
      <version>1.0</version>
</dependency>

If you're not interested in building JNC using maven, then you can abandon pull request #41.

**Comment by klacke** [comment]
I'm not interested - yes - but other may be, I'll check ....

**Pull request merged**
