### PR TITLE
Updating Java source for maven compatibility

### LINKED ISSUE #1: Build System
Feature Request to move from Ant to Maven Multiproject.  

Will allow support out of the box: 
- All IDE configuration files, Eclipse, IDEAJ, etc.
- Publishing of Milestone releases (versioning)
- Easier integration of 3rd party dependencies
- Std project layout

### PR DESCRIPTION
**Pull request by bocon13**
The pull requests reorganizes the Java sources to match the Maven standard project structure (src/main/java/...). It also updates ant's build.xml with the new source locations. The pom.xml (for Maven) has been updated so that Maven can be used to properly compile, test, package (as a jar) and release the JNC library (i.e. it allows you to use maven as the build framework).

The README has been updated for maven build instructions, as well as more specific manual build instructions. Finally, some additional files and directories were added to .gitignore

fixes #1 -- allows either ant or maven to be used as the build framework

### CODE REVIEW

**Comment by klacke** [comment]
Will check ....

**Comment by chrisinmtown** [comment]
I need a Java Netconf client but have to ask, is this project still alive? As of this writing the most recent commit is over 3 years ago, there are many open merge requests like this one, and at best a community member (not a maintainer) responds to open issues. I glean from those issues that the project requires Python 2 (which went end-of-life in January 2020) and uses the old-fashioned Ant instead of Maven to build.

**Comment by 243826** [comment]
check out this project - which largely uses the jnc engine underneath but provides the async API and netconf 1.1 support.

**Comment by 243826** [comment]
@chrisinmtown @bocon13 please check out https://github.com/Celeral/NetConf-Async and let me know if you find it useful.

**Comment by chrisinmtown** [comment]
@243826 Chetan thanks for the link. You might also consider making a pull request or two here, maybe update some minor issues like Java9/Java11 compatibility.  Even if your PR is never merged, it still provides a pointer to your version for people like me.

**Comment by micnovak** [comment]
This request was implemented in release 1.1.0 (code structure reworked to reflect gradle compatibility, which is the same as maven).

**Pull request closed without merging**
